[package]
name = "sqfs"
version = "0.0.1"
authors = ["Emil Renner Berthing <esmil@mailme.dk>"]

[dependencies]
time = "*"
clap = "*"
byteorder = "*"
libz-sys = "*"
lzma-sys = "*"
rust-lzo = "*"
lz4-sys = "*"
yaml-rust = "*"

[lib]
name = "squashfs"

[[bin]]
name = "sqfs"
